"""Add notifications table

Revision ID: 0905f2d02723
Revises: e5023d780434
Create Date: 2025-02-28 12:18:39.762953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0905f2d02723'
down_revision: Union[str, None] = 'e5023d780434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('receiver_departments', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('notifications', sa.Column('responses', sa.JSON(), nullable=True))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.drop_constraint('notifications_patient_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['sender_id'], ['id'])
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'recipient')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'patient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('notification_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('recipient', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_patient_id_fkey', 'notifications', 'patients', ['patient_id'], ['patient_id'])
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.alter_column('notifications', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'responses')
    op.drop_column('notifications', 'receiver_departments')
    op.drop_column('notifications', 'sender_id')
    # ### end Alembic commands ###
