"""add_is_paid_to_pharmacy_records

Revision ID: 0fb857192304
Revises: 0905f2d02723
Create Date: 2025-03-01 08:51:48.803290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb857192304'
down_revision: Union[str, None] = '0905f2d02723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacy_records', sa.Column('is_paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacy_records', 'is_paid')
    # ### end Alembic commands ###
