"""Describe the changes made

Revision ID: 2f2386c18a69
Revises: b9050834a7ec
Create Date: 2025-02-16 07:26:05.780311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2386c18a69'
down_revision: Union[str, None] = 'b9050834a7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('billings', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_unique_constraint(None, 'doctors', ['full_name'])
    op.alter_column('nurses', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('patients', sa.Column('nurse_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'nurses', ['nurse_id'], ['id'])
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'nurse_id')
    op.alter_column('nurses', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'doctors', type_='unique')
    op.drop_column('billings', 'discount_amount')
    op.drop_column('billings', 'discount_percentage')
    # ### end Alembic commands ###
