"""Make prescribed_date nullable in drugs table

Revision ID: 86aa3f8b9c2b
Revises: cee1c2a16d7b
Create Date: 2025-02-27 16:18:12.098025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86aa3f8b9c2b'
down_revision: Union[str, None] = 'cee1c2a16d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pharmacy_sales')
    op.alter_column('drugs', 'prescribed_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_unique_constraint(None, 'drugs', ['name'])
    op.add_column('pharmacy_records', sa.Column('drug_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pharmacy_records', 'drugs', ['drug_id'], ['id'])
    op.alter_column('stock', 'drug_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock', 'drug_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'pharmacy_records', type_='foreignkey')
    op.drop_column('pharmacy_records', 'drug_id')
    op.drop_constraint(None, 'drugs', type_='unique')
    op.alter_column('drugs', 'prescribed_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_table('pharmacy_sales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pharmacy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('drug_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name='pharmacy_sales_drug_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacy_records.pharmacy_id'], name='pharmacy_sales_pharmacy_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pharmacy_sales_pkey')
    )
    # ### end Alembic commands ###
