"""Set default status to Unpaid in Billing

Revision ID: 96eb93baa1ee
Revises: e8ef48dc7e65
Create Date: 2025-03-02 08:41:52.328879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96eb93baa1ee'
down_revision: Union[str, None] = 'e8ef48dc7e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payment_histories', ['receipt_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_histories', type_='unique')
    # ### end Alembic commands ###
