"""billling updated

Revision ID: 9992b3cb3933
Revises: 86aa3f8b9c2b
Create Date: 2025-02-28 06:40:36.684475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9992b3cb3933'
down_revision: Union[str, None] = '86aa3f8b9c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('billings', sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('billings', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billings', 'status')
    op.drop_column('billings', 'amount_due')
    op.drop_column('billings', 'amount')
    # ### end Alembic commands ###
