"""Add nurse_id column to patients table

Revision ID: b9050834a7ec
Revises: 6e454b991450
Create Date: 2025-02-16 06:59:49.282812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9050834a7ec'
down_revision: Union[str, None] = '6e454b991450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('billings', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('doctors', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'doctors', ['full_name'])
    op.add_column('patients', sa.Column('nurse_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'nurses', ['nurse_id'], ['id'])
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'nurse_id')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.alter_column('doctors', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('billings', 'discount_amount')
    op.drop_column('billings', 'discount_percentage')
    # ### end Alembic commands ###
