"""Removed Drug.patients relationship

Revision ID: cee1c2a16d7b
Revises: e7b604ff9e26
Create Date: 2025-02-27 09:09:28.606371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee1c2a16d7b'
down_revision: Union[str, None] = 'e7b604ff9e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pharmacy_sales')
    op.create_unique_constraint(None, 'drugs', ['name'])
    op.add_column('pharmacy_records', sa.Column('drug_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pharmacy_records', 'drugs', ['drug_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pharmacy_records', type_='foreignkey')
    op.drop_column('pharmacy_records', 'drug_id')
    op.drop_constraint(None, 'drugs', type_='unique')
    op.create_table('pharmacy_sales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pharmacy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('drug_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name='pharmacy_sales_drug_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacy_records.pharmacy_id'], name='pharmacy_sales_pharmacy_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pharmacy_sales_pkey')
    )
    # ### end Alembic commands ###
