"""Add created_at and updated_at columns

Revision ID: e075e3c6d2e2
Revises: 978e73cbc68e
Create Date: 2025-02-10 00:27:39.470796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e075e3c6d2e2'
down_revision: Union[str, None] = '978e73cbc68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('billings', sa.Column('doctor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'billings', 'doctors', ['doctor_id'], ['id'])
    op.add_column('clinical_notes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('clinical_notes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('clinical_notes', sa.Column('billing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clinical_notes', 'billings', ['billing_id'], ['billing_id'], ondelete='CASCADE')
    op.add_column('laboratory_records', sa.Column('billing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'laboratory_records', 'billings', ['billing_id'], ['billing_id'], ondelete='CASCADE')
    op.add_column('mental_health', sa.Column('billing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mental_health', 'billings', ['billing_id'], ['billing_id'], ondelete='CASCADE')
    op.add_column('occupational_therapy_records', sa.Column('billing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'occupational_therapy_records', 'billings', ['billing_id'], ['billing_id'], ondelete='CASCADE')
    op.add_column('pharmacy_records', sa.Column('billing_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pharmacy_records', 'billings', ['billing_id'], ['billing_id'])
    op.add_column('psychology_records', sa.Column('billing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'psychology_records', 'billings', ['billing_id'], ['billing_id'], ondelete='CASCADE')
    op.add_column('social_work_records', sa.Column('billing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'social_work_records', 'billings', ['billing_id'], ['billing_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_work_records', type_='foreignkey')
    op.drop_column('social_work_records', 'billing_id')
    op.drop_constraint(None, 'psychology_records', type_='foreignkey')
    op.drop_column('psychology_records', 'billing_id')
    op.drop_constraint(None, 'pharmacy_records', type_='foreignkey')
    op.drop_column('pharmacy_records', 'billing_id')
    op.drop_constraint(None, 'occupational_therapy_records', type_='foreignkey')
    op.drop_column('occupational_therapy_records', 'billing_id')
    op.drop_constraint(None, 'mental_health', type_='foreignkey')
    op.drop_column('mental_health', 'billing_id')
    op.drop_constraint(None, 'laboratory_records', type_='foreignkey')
    op.drop_column('laboratory_records', 'billing_id')
    op.drop_constraint(None, 'clinical_notes', type_='foreignkey')
    op.drop_column('clinical_notes', 'billing_id')
    op.drop_column('clinical_notes', 'updated_at')
    op.drop_column('clinical_notes', 'created_at')
    op.drop_constraint(None, 'billings', type_='foreignkey')
    op.drop_column('billings', 'doctor_id')
    # ### end Alembic commands ###
