"""Updated drug and pharmacy models

Revision ID: e7b604ff9e26
Revises: 616abb74c776
Create Date: 2025-02-27 04:58:42.800305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b604ff9e26'
down_revision: Union[str, None] = '616abb74c776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pharmacy_sales')
    op.alter_column('drugs', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'drugs', ['name'])
    op.add_column('pharmacy_records', sa.Column('drug_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pharmacy_records', 'drugs', ['drug_id'], ['id'])
    op.drop_column('pharmacy_records', 'medication_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacy_records', sa.Column('medication_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pharmacy_records', type_='foreignkey')
    op.drop_column('pharmacy_records', 'drug_id')
    op.drop_constraint(None, 'drugs', type_='unique')
    op.alter_column('drugs', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('pharmacy_sales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pharmacy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('drug_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name='pharmacy_sales_drug_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacy_records.pharmacy_id'], name='pharmacy_sales_pharmacy_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pharmacy_sales_pkey')
    )
    # ### end Alembic commands ###
